language: node_js
node_js:
  - 6
sudo: false
services:
  - mysql
  - redis
mysql:
  - adapter: mysql2
  - username: sotrade
  - database: sotrade
  - encoding: utf8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - liblapack-dev
      - g++-4.8
      - libstdc++-4.8-dev
cache:
  directories:
    - node_modules
before_install:
  - export PATH="$HOME/.local/bin:./node_modules/.bin:$PATH"
  - export CXX="g++-4.8" CC="gcc-4.8"
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS sotrade_test'
script:
  - ./config.js
  - npm run jshint
  - npm run test-cov
after_success:
  - npm install coveralls
  - nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
